name: Answers
on:
  workflow_dispatch:


jobs:
  answer:
    runs-on: ubuntu-latest
    steps:
      - env:
          SECRET: ${{ secrets.Secret }}
        run: |
          echo "The answer is $SECRET"
          OUTPUT=$SECRET
          echo "${OUTPUT}"
